"""
Enhanced SIC Code Lookup with Full 4-Digit Classification
Maps all detected SIC codes from SEC data to industry names and sectors
"""

import pandas as pd
import os

def create_comprehensive_sic_lookup() -> pd.DataFrame:
    """
    Create comprehensive SIC code mapping for all 4-digit codes
    Based on U.S. Commerce Department SIC Manual
    """
    
    sic_data = {
        # Agriculture (0100-0999)
        '0100': ('Agricultural Production - Crops', 'Agriculture', '01'),
        '0110': ('Wheat', 'Agriculture', '01'),
        '0130': ('Field Crops, Except Cash Grains', 'Agriculture', '01'),
        '0200': ('Agricultural Production - Livestock', 'Agriculture', '02'),
        '0210': ('Beef Cattle Feedlots', 'Agriculture', '02'),
        '0270': ('Animal Aquaculture', 'Agriculture', '02'),
        '0700': ('Agricultural Services', 'Agriculture', '07'),
        '0710': ('Soil Preparation Services', 'Agriculture', '07'),
        '0800': ('Forestry', 'Agriculture', '08'),
        '0900': ('Fishing, Hunting, Trapping', 'Agriculture', '09'),
        '0910': ('Fish Hatcheries & Preserves', 'Agriculture', '09'),
        
        # Mining (1000-1499)
        '1000': ('Metal Mining', 'Mining', '10'),
        '1010': ('Iron Ores', 'Mining', '10'),
        '1020': ('Copper Ores', 'Mining', '10'),
        '1030': ('Lead & Zinc Ores', 'Mining', '10'),
        '1040': ('Gold Ores', 'Mining', '10'),
        '1050': ('Bauxite & Other Aluminum Ores', 'Mining', '10'),
        '1060': ('Ferroalloy Ores', 'Mining', '10'),
        '1090': ('Misc Metallic Ores', 'Mining', '10'),
        '1100': ('Anthracite Mining', 'Mining', '11'),
        '1200': ('Bituminous Coal & Lignite Mining', 'Mining', '12'),
        '1210': ('Bituminous Coal Mining', 'Mining', '12'),
        '1220': ('Lignite Mining', 'Mining', '12'),
        '1300': ('Oil & Gas Extraction', 'Mining', '13'),
        '1310': ('Crude Oil & Natural Gas', 'Mining', '13'),
        '1320': ('Natural Gas Liquids', 'Mining', '13'),
        '1380': ('Oil & Gas Field Services', 'Mining', '13'),
        '1389': ('Oil & Gas Field Services NEC', 'Mining', '13'),
        '1400': ('Nonmetallic Minerals', 'Mining', '14'),
        '1410': ('Dimension Stone', 'Mining', '14'),
        '1420': ('Crushed & Broken Stone', 'Mining', '14'),
        '1440': ('Sand & Gravel', 'Mining', '14'),
        '1450': ('Clay, Ceramic, Refractory Minerals', 'Mining', '14'),
        '1470': ('Chemical & Fertilizer Minerals', 'Mining', '14'),
        '1480': ('Salt Mining', 'Mining', '14'),
        '1490': ('Misc Nonmetallic Minerals', 'Mining', '14'),
        
        # Construction (1500-1799)
        '1500': ('General Building Contractors', 'Construction', '15'),
        '1510': ('General Contractors - Single Family', 'Construction', '15'),
        '1520': ('General Contractors - Residential', 'Construction', '15'),
        '1530': ('General Contractors - Nonresidential', 'Construction', '15'),
        '1600': ('Heavy Construction', 'Construction', '16'),
        '1610': ('Highway & Street Construction', 'Construction', '16'),
        '1620': ('Bridge, Tunnel, Elevated Hwy Construction', 'Construction', '16'),
        '1629': ('Heavy Construction NEC', 'Construction', '16'),
        '1700': ('Special Trade Contractors', 'Construction', '17'),
        '1711': ('Plumbing, Heating, AC', 'Construction', '17'),
        '1721': ('Painting & Paper Hanging', 'Construction', '17'),
        '1731': ('Electrical Contractors', 'Construction', '17'),
        '1740': ('Masonry, Stonework, Tile Setting', 'Construction', '17'),
        '1750': ('Carpentry & Floor Work', 'Construction', '17'),
        '1760': ('Roofing, Sheet Metal, Structural Steel', 'Construction', '17'),
        '1770': ('Concrete Work', 'Construction', '17'),
        '1790': ('Miscellaneous Special Trade', 'Construction', '17'),
        
        # Food & Kindred Products (2000-2099)
        '2000': ('Meat Products', 'Manufacturing', '20'),
        '2010': ('Meat Packing Plants', 'Manufacturing', '20'),
        '2011': ('Sausage & Other Prepared Meats', 'Manufacturing', '20'),
        '2013': ('Sausage & Other Prepared Meats', 'Manufacturing', '20'),
        '2020': ('Poultry & Egg Processing', 'Manufacturing', '20'),
        '2030': ('Canned & Preserved Fruits, Vegetables', 'Manufacturing', '20'),
        '2033': ('Canned Fruits, Vegetables, Preserves', 'Manufacturing', '20'),
        '2037': ('Frozen Fruits, Fruit Juices', 'Manufacturing', '20'),
        '2038': ('Frozen Specialties', 'Manufacturing', '20'),
        '2040': ('Grain Mill Products', 'Manufacturing', '20'),
        '2041': ('Flour & Other Grain Products', 'Manufacturing', '20'),
        '2043': ('Cereal Breakfast Foods', 'Manufacturing', '20'),
        '2044': ('Rice Milling', 'Manufacturing', '20'),
        '2045': ('Blended & Prepared Flour', 'Manufacturing', '20'),
        '2046': ('Wet Corn Milling', 'Manufacturing', '20'),
        '2048': ('Fats & Oils', 'Manufacturing', '20'),
        '2050': ('Bakery Products', 'Manufacturing', '20'),
        '2051': ('Bread & Other Bakery Products', 'Manufacturing', '20'),
        '2052': ('Cookies & Crackers', 'Manufacturing', '20'),
        '2060': ('Sugar Processing', 'Manufacturing', '20'),
        '2061': ('Cane Sugar Refining', 'Manufacturing', '20'),
        '2062': ('Beet Sugar', 'Manufacturing', '20'),
        '2065': ('Confectionery Products', 'Manufacturing', '20'),
        '2066': ('Chocolate & Cocoa Products', 'Manufacturing', '20'),
        '2067': ('Chewing Gum', 'Manufacturing', '20'),
        '2070': ('Beverage Industries', 'Manufacturing', '20'),
        '2080': ('Beverage Industries', 'Manufacturing', '20'),
        '2086': ('Beverage Bottling & Canning', 'Manufacturing', '20'),
        '2087': ('Flavoring Extracts & Syrups', 'Manufacturing', '20'),
        '2090': ('Miscellaneous Food Preparations', 'Manufacturing', '20'),
        '2095': ('Coffee & Tea', 'Manufacturing', '20'),
        '2098': ('Macaroni, Spaghetti, Noodles', 'Manufacturing', '20'),
        
        # Tobacco Products (2100-2199)
        '2110': ('Cigarettes', 'Manufacturing', '21'),
        '2121': ('Cigars', 'Manufacturing', '21'),
        '2131': ('Chewing & Smoking Tobacco', 'Manufacturing', '21'),
        
        # Textile Mill Products (2200-2299)
        '2200': ('Textile Mill Products', 'Manufacturing', '22'),
        '2211': ('Broadwoven Fabric Mills', 'Manufacturing', '22'),
        '2221': ('Narrow Woven Fabric Mills', 'Manufacturing', '22'),
        '2231': ('Wool Yarn Mills', 'Manufacturing', '22'),
        '2241': ('Throwing & Twisting Mills', 'Manufacturing', '22'),
        '2251': ('Woman Hosiery Mills', 'Manufacturing', '22'),
        '2252': ('Hosiery & Sock Mills', 'Manufacturing', '22'),
        '2261': ('Finishing Plants - Textiles', 'Manufacturing', '22'),
        '2273': ('Carpets & Rugs', 'Manufacturing', '22'),
        '2281': ('Yarn & Thread Mills', 'Manufacturing', '22'),
        '2295': ('Coated Fabrics', 'Manufacturing', '22'),
        '2296': ('Tire Cord & Fabric', 'Manufacturing', '22'),
        '2297': ('Nonwoven Fabrics', 'Manufacturing', '22'),
        '2298': ('Cordage & Twine', 'Manufacturing', '22'),
        '2299': ('Textile Goods NEC', 'Manufacturing', '22'),
        
        # Apparel & Other Fabricated (2300-2399)
        '2311': ('Men\'s & Boys\' Suits, Coats, Jackets', 'Manufacturing', '23'),
        '2321': ('Men\'s & Boys\' Shirts', 'Manufacturing', '23'),
        '2322': ('Men\'s & Boys\' Underwear', 'Manufacturing', '23'),
        '2329': ('Men\'s Clothing NEC', 'Manufacturing', '23'),
        '2331': ('Women\'s, Misses\' Blouses & Shirts', 'Manufacturing', '23'),
        '2335': ('Women\'s, Misses\' Dresses', 'Manufacturing', '23'),
        '2337': ('Women\'s, Misses\' Suits, Skirts, Coats', 'Manufacturing', '23'),
        '2339': ('Women\'s Clothing NEC', 'Manufacturing', '23'),
        '2341': ('Children\'s Uniforms & Other Clothing', 'Manufacturing', '23'),
        '2342': ('Brassieres, Girdles, Allied Garments', 'Manufacturing', '23'),
        '2353': ('Hats, Caps, Millinery', 'Manufacturing', '23'),
        '2361': ('Leather & Sheep-Lined Clothing', 'Manufacturing', '23'),
        '2369': ('Apparel & Accessories NEC', 'Manufacturing', '23'),
        '2381': ('Fabric Dress & Work Gloves', 'Manufacturing', '23'),
        '2384': ('Robes & Dressing Gowns', 'Manufacturing', '23'),
        '2385': ('Waterproof Outerwear', 'Manufacturing', '23'),
        '2386': ('Leather & Sheep-Lined Clothing', 'Manufacturing', '23'),
        '2387': ('Apparel Belts', 'Manufacturing', '23'),
        '2389': ('Apparel & Accessories NEC', 'Manufacturing', '23'),
        '2391': ('Curtains & Draperies', 'Manufacturing', '23'),
        '2392': ('Housefurnishings NEC', 'Manufacturing', '23'),
        '2393': ('Textile Bags', 'Manufacturing', '23'),
        '2394': ('Canvas & Related Products', 'Manufacturing', '23'),
        '2395': ('Pleating, Decorative & Novelty Stitching', 'Manufacturing', '23'),
        '2396': ('Automotive Trimmings', 'Manufacturing', '23'),
        '2397': ('Schiffli Machine Embroideries', 'Manufacturing', '23'),
        '2399': ('Fabricated Textile Products NEC', 'Manufacturing', '23'),
        
        # Lumber & Wood Products (2400-2499)
        '2411': ('Logging', 'Manufacturing', '24'),
        '2421': ('Sawmills & Planing Mills', 'Manufacturing', '24'),
        '2426': ('Hardwood Dimension & Flooring Mills', 'Manufacturing', '24'),
        '2429': ('Special Product Sawmills', 'Manufacturing', '24'),
        '2431': ('Millwork', 'Manufacturing', '24'),
        '2434': ('Wood Kitchen Cabinets', 'Manufacturing', '24'),
        '2435': ('Hardwood Veneer & Plywood', 'Manufacturing', '24'),
        '2436': ('Softwood Veneer & Plywood', 'Manufacturing', '24'),
        '2439': ('Structural Wood Members NEC', 'Manufacturing', '24'),
        '2441': ('Nailed Wood Boxes & Shook', 'Manufacturing', '24'),
        '2448': ('Wood Pallets & Skids', 'Manufacturing', '24'),
        '2449': ('Wood Containers NEC', 'Manufacturing', '24'),
        '2451': ('Mobile Homes', 'Manufacturing', '24'),
        '2452': ('Prefabricated Wood Buildings', 'Manufacturing', '24'),
        '2491': ('Wood Preserving', 'Manufacturing', '24'),
        '2499': ('Wood Products NEC', 'Manufacturing', '24'),
        
        # Furniture & Fixtures (2500-2599)
        '2511': ('Wood Household Furniture', 'Manufacturing', '25'),
        '2512': ('Upholstered Household Furniture', 'Manufacturing', '25'),
        '2514': ('Metal Household Furniture', 'Manufacturing', '25'),
        '2515': ('Mattresses & Bedsprings', 'Manufacturing', '25'),
        '2517': ('Wood Television Stands', 'Manufacturing', '25'),
        '2519': ('Household Furniture NEC', 'Manufacturing', '25'),
        '2521': ('Wood Office Furniture', 'Manufacturing', '25'),
        '2522': ('Office Furniture - Metal', 'Manufacturing', '25'),
        '2531': ('Public Building & Related Furniture', 'Manufacturing', '25'),
        '2541': ('Wood Office & Store Fixtures', 'Manufacturing', '25'),
        '2542': ('Metal Office & Store Fixtures', 'Manufacturing', '25'),
        '2591': ('Drapery Hardware & Blinds', 'Manufacturing', '25'),
        '2599': ('Furniture & Fixtures NEC', 'Manufacturing', '25'),
        
        # Paper (2600-2699)
        '2611': ('Pulp Mills', 'Manufacturing', '26'),
        '2621': ('Paper Mills', 'Manufacturing', '26'),
        '2631': ('Paperboard Mills', 'Manufacturing', '26'),
        '2641': ('Paper Coating & Glazing', 'Manufacturing', '26'),
        '2652': ('Setup Paperboard Boxes', 'Manufacturing', '26'),
        '2653': ('Corrugated & Solid Fiber Boxes', 'Manufacturing', '26'),
        '2655': ('Fiber Cans, Tubes, Drums', 'Manufacturing', '26'),
        '2656': ('Sanitary Paper Products', 'Manufacturing', '26'),
        '2657': ('Envelopes', 'Manufacturing', '26'),
        '2671': ('Packaging Paper & Plastic Film', 'Manufacturing', '26'),
        '2672': ('Coated & Laminated Paper', 'Manufacturing', '26'),
        '2673': ('Bags: Plastic, Laminated, & Coated', 'Manufacturing', '26'),
        '2674': ('Bags: Uncoated Paper & Multiwall', 'Manufacturing', '26'),
        '2675': ('Die-Cut Paper & Paperboard', 'Manufacturing', '26'),
        '2676': ('Sanitary Paper Products', 'Manufacturing', '26'),
        '2677': ('Envelopes', 'Manufacturing', '26'),
        '2678': ('Stationery Products', 'Manufacturing', '26'),
        '2679': ('Paper Products NEC', 'Manufacturing', '26'),
        
        # Printing & Publishing (2700-2799)
        '2711': ('Newspapers', 'Manufacturing', '27'),
        '2721': ('Periodicals', 'Manufacturing', '27'),
        '2731': ('Books Publishing', 'Manufacturing', '27'),
        '2732': ('Book Printing', 'Manufacturing', '27'),
        '2741': ('Miscellaneous Publishing', 'Manufacturing', '27'),
        '2752': ('Commercial Printing - Lithographic', 'Manufacturing', '27'),
        '2754': ('Commercial Printing - Gravure', 'Manufacturing', '27'),
        '2759': ('Commercial Printing NEC', 'Manufacturing', '27'),
        '2761': ('Manifold Business Forms', 'Manufacturing', '27'),
        '2771': ('Greeting Cards', 'Manufacturing', '27'),
        '2782': ('Blankbooks & Looseleaf Binders', 'Manufacturing', '27'),
        '2789': ('Bookbinding & Finishing', 'Manufacturing', '27'),
        '2791': ('Typesetting', 'Manufacturing', '27'),
        '2796': ('Platemaking & Related Services', 'Manufacturing', '27'),
        '2797': ('Printing Trade Services', 'Manufacturing', '27'),
        '2799': ('Printing & Publishing NEC', 'Manufacturing', '27'),
        
        # Chemicals & Allied Products (2800-2899)
        '2812': ('Alkalies & Chlorine', 'Manufacturing', '28'),
        '2813': ('Industrial Gases', 'Manufacturing', '28'),
        '2816': ('Inorganic Pigments', 'Manufacturing', '28'),
        '2819': ('Industrial Inorganic Chemicals NEC', 'Manufacturing', '28'),
        '2821': ('Plastics Materials & Thermoset Resins', 'Manufacturing', '28'),
        '2822': ('Synthetic Rubber', 'Manufacturing', '28'),
        '2823': ('Cellulosic Manmade Fibers', 'Manufacturing', '28'),
        '2824': ('Manmade Organic Fibers', 'Manufacturing', '28'),
        '2833': ('Medicinal Chemicals & Botanical', 'Manufacturing', '28'),
        '2834': ('Pharmaceutical Preparations', 'Manufacturing', '28'),
        '2835': ('In Vitro & In Vivo Diagnostics', 'Manufacturing', '28'),
        '2836': ('Biological Products', 'Manufacturing', '28'),
        '2841': ('Soap & Other Detergents', 'Manufacturing', '28'),
        '2842': ('Specialty Cleaning Preparations', 'Manufacturing', '28'),
        '2843': ('Surface Active Agents', 'Manufacturing', '28'),
        '2844': ('Perfume, Cosmetics, Toilet Preparations', 'Manufacturing', '28'),
        '2851': ('Paints, Varnishes, Lacquers', 'Manufacturing', '28'),
        '2861': ('Gum & Wood Chemicals', 'Manufacturing', '28'),
        '2865': ('Cyclic Crudes & Intermediates', 'Manufacturing', '28'),
        '2869': ('Industrial Organic Chemicals NEC', 'Manufacturing', '28'),
        '2873': ('Nitrogenous Fertilizers', 'Manufacturing', '28'),
        '2874': ('Phosphatic Fertilizers', 'Manufacturing', '28'),
        '2875': ('Fertilizers, Mixed', 'Manufacturing', '28'),
        '2879': ('Pesticides & Agricultural Chemicals', 'Manufacturing', '28'),
        '2891': ('Adhesives & Sealants', 'Manufacturing', '28'),
        '2892': ('Explosives', 'Manufacturing', '28'),
        '2893': ('Printing Ink', 'Manufacturing', '28'),
        '2895': ('Carbon Black', 'Manufacturing', '28'),
        '2899': ('Chemical Products NEC', 'Manufacturing', '28'),
        
        # Petrol & Coal Products (2900-2999)
        '2911': ('Petroleum Refining', 'Manufacturing', '29'),
        '2951': ('Asphalt Paving & Roofing Materials', 'Manufacturing', '29'),
        '2952': ('Asphalt & Tar Products', 'Manufacturing', '29'),
        '2992': ('Lubricating Oils & Greases', 'Manufacturing', '29'),
        '2999': ('Petrochemical Products NEC', 'Manufacturing', '29'),
        
        # Rubber & Plastics (3000-3099)
        '3011': ('Tires & Inner Tubes', 'Manufacturing', '30'),
        '3021': ('Rubber & Plastic Footwear', 'Manufacturing', '30'),
        '3052': ('Rubber & Plastic Hose & Belting', 'Manufacturing', '30'),
        '3053': ('Gaskets, Packing, Sealing Devices', 'Manufacturing', '30'),
        '3061': ('Molded, Extruded Rubber Products', 'Manufacturing', '30'),
        '3069': ('Rubber Products NEC', 'Manufacturing', '30'),
        '3081': ('Unsupported Plastics Film & Sheet', 'Manufacturing', '30'),
        '3082': ('Unsupported Plastics Shapes & Forms', 'Manufacturing', '30'),
        '3083': ('Laminated Plastics Plate, Sheet, & Rod', 'Manufacturing', '30'),
        '3084': ('Plastics Pipe', 'Manufacturing', '30'),
        '3085': ('Plastics Bottle & Closures', 'Manufacturing', '30'),
        '3086': ('Plastics Foam Products', 'Manufacturing', '30'),
        '3087': ('Custom Compound Purchased Resins', 'Manufacturing', '30'),
        '3088': ('Plastics Plumbing Fixtures', 'Manufacturing', '30'),
        '3089': ('Plastics Products NEC', 'Manufacturing', '30'),
        
        # Leather & Shoes (3100-3199)
        '3111': ('Leather Tanning & Finishing', 'Manufacturing', '31'),
        '3131': ('Boot & Shoe Cut Stock & Findings', 'Manufacturing', '31'),
        '3142': ('House Slippers', 'Manufacturing', '31'),
        '3143': ('Men\'s Footwear', 'Manufacturing', '31'),
        '3144': ('Women\'s Footwear', 'Manufacturing', '31'),
        '3149': ('Footwear NEC', 'Manufacturing', '31'),
        '3151': ('Leather Gloves & Mittens', 'Manufacturing', '31'),
        '3161': ('Luggage', 'Manufacturing', '31'),
        '3171': ('Women\'s Handbags & Purses', 'Manufacturing', '31'),
        '3172': ('Personal Leather Goods', 'Manufacturing', '31'),
        '3199': ('Leather & Leather Products NEC', 'Manufacturing', '31'),
        
        # Stone, Clay, Glass (3200-3299)
        '3211': ('Flat Glass', 'Manufacturing', '32'),
        '3212': ('Glass Containers', 'Manufacturing', '32'),
        '3213': ('Glass Products Made of Purchased Glass', 'Manufacturing', '32'),
        '3221': ('Ceramic Wall & Floor Tile', 'Manufacturing', '32'),
        '3229': ('Pressed & Blown Glass & Glassware NEC', 'Manufacturing', '32'),
        '3231': ('Pottery Products', 'Manufacturing', '32'),
        '3241': ('Cement, Hydraulic', 'Manufacturing', '32'),
        '3251': ('Brick & Structural Clay Tile', 'Manufacturing', '32'),
        '3253': ('Ceramic Wall & Floor Tile', 'Manufacturing', '32'),
        '3261': ('Vitreous Plumbing Fixtures', 'Manufacturing', '32'),
        '3262': ('Vitreous Ceramic Laboratory Apparatus', 'Manufacturing', '32'),
        '3269': ('Pottery Products NEC', 'Manufacturing', '32'),
        '3271': ('Concrete Block & Brick', 'Manufacturing', '32'),
        '3272': ('Concrete Products NEC', 'Manufacturing', '32'),
        '3281': ('Cut Stone & Stone Products', 'Manufacturing', '32'),
        '3291': ('Abrasive Products', 'Manufacturing', '32'),
        '3297': ('Nonclay Refractories', 'Manufacturing', '32'),
        '3299': ('Nonmetallic Mineral Products NEC', 'Manufacturing', '32'),
        
        # Primary Metal Industries (3300-3399)
        '3312': ('Steel Works, Blast Furnaces, Rolling Mills', 'Manufacturing', '33'),
        '3313': ('Electrometallurgical Products', 'Manufacturing', '33'),
        '3315': ('Steel Wire & Related Products', 'Manufacturing', '33'),
        '3316': ('Cold-Rolled Steel Sheet, Strip, & Bars', 'Manufacturing', '33'),
        '3317': ('Steel Pipe & Tubes', 'Manufacturing', '33'),
        '3321': ('Gray Iron Foundries', 'Manufacturing', '33'),
        '3322': ('Ductile Iron Foundries', 'Manufacturing', '33'),
        '3323': ('Steel Investment Foundries', 'Manufacturing', '33'),
        '3324': ('Steel Foundries NEC', 'Manufacturing', '33'),
        '3325': ('Steel Castings', 'Manufacturing', '33'),
        '3331': ('Primary Smelting & Refining Copper', 'Manufacturing', '33'),
        '3339': ('Primary Nonferrous Metals NEC', 'Manufacturing', '33'),
        '3341': ('Secondary Nonferrous Metals', 'Manufacturing', '33'),
        '3351': ('Rolling, Drawing, Extruding Copper', 'Manufacturing', '33'),
        '3353': ('Aluminum Sheet, Plate, & Foil', 'Manufacturing', '33'),
        '3354': ('Aluminum Extruded Products', 'Manufacturing', '33'),
        '3355': ('Rolling, Drawing, Extruding Other Nonferrous', 'Manufacturing', '33'),
        '3356': ('Nonferrous Wire Drawing & Insulating', 'Manufacturing', '33'),
        '3357': ('Nonferrous Wiredrawing & Insulating', 'Manufacturing', '33'),
        '3363': ('Aluminum Die-Castings', 'Manufacturing', '33'),
        '3364': ('Nonferrous Die-Casting', 'Manufacturing', '33'),
        '3365': ('Aluminum Foundries', 'Manufacturing', '33'),
        '3366': ('Copper Foundries', 'Manufacturing', '33'),
        '3369': ('Nonferrous Foundries NEC', 'Manufacturing', '33'),
        '3398': ('Metal Heat Treating', 'Manufacturing', '33'),
        '3399': ('Primary Metal Industries NEC', 'Manufacturing', '33'),
        
        # Fabricated Metal Products (3400-3499)
        '3411': ('Metal Cans', 'Manufacturing', '34'),
        '3412': ('Metal Barrels, Drums, Pails', 'Manufacturing', '34'),
        '3421': ('Cutlery', 'Manufacturing', '34'),
        '3423': ('Hand & Edge Tools', 'Manufacturing', '34'),
        '3425': ('Saw Blades & Handsaws', 'Manufacturing', '34'),
        '3429': ('Hand & Edge Tools NEC', 'Manufacturing', '34'),
        '3431': ('Enameled Iron & Metal Products', 'Manufacturing', '34'),
        '3432': ('Plumbing Fittings & Brass Goods', 'Manufacturing', '34'),
        '3433': ('Heating Equipment & Supplies', 'Manufacturing', '34'),
        '3441': ('Fabricated Structural Metal', 'Manufacturing', '34'),
        '3442': ('Metal Doors, Sashes, Frames, Trim', 'Manufacturing', '34'),
        '3443': ('Fabricated Plate Work', 'Manufacturing', '34'),
        '3444': ('Sheet Metal Work', 'Manufacturing', '34'),
        '3446': ('Architectural & Ornamental Metal', 'Manufacturing', '34'),
        '3448': ('Prefabricated Metal Buildings', 'Manufacturing', '34'),
        '3451': ('Screw Machine Products', 'Manufacturing', '34'),
        '3452': ('Bolts, Nuts, Screws, Rivets, Washers', 'Manufacturing', '34'),
        '3461': ('Metal Forging & Stamping', 'Manufacturing', '34'),
        '3462': ('Iron & Steel Forgings', 'Manufacturing', '34'),
        '3463': ('Nonferrous Forgings', 'Manufacturing', '34'),
        '3465': ('Automotive Stampings', 'Manufacturing', '34'),
        '3466': ('Crowns & Closures', 'Manufacturing', '34'),
        '3469': ('Metal Stampings NEC', 'Manufacturing', '34'),
        '3471': ('Electroplating, Plating, Polishing', 'Manufacturing', '34'),
        '3472': ('Metal Coating & Allied Services', 'Manufacturing', '34'),
        '3479': ('Coating, Engraving, & Allied Services NEC', 'Manufacturing', '34'),
        '3482': ('Small Arms Ammunition', 'Manufacturing', '34'),
        '3483': ('Ammunition NEC', 'Manufacturing', '34'),
        '3484': ('Small Arms', 'Manufacturing', '34'),
        '3489': ('Ordnance & Accessories NEC', 'Manufacturing', '34'),
        '3491': ('Industrial Valves', 'Manufacturing', '34'),
        '3492': ('Fluid Power Valves', 'Manufacturing', '34'),
        '3493': ('Steel Springs', 'Manufacturing', '34'),
        '3494': ('Valves & Pipe Fittings NEC', 'Manufacturing', '34'),
        '3495': ('Wire Springs', 'Manufacturing', '34'),
        '3496': ('Miscellaneous Fabricated Wire', 'Manufacturing', '34'),
        '3497': ('Metal Foil & Leaf', 'Manufacturing', '34'),
        '3498': ('Fabricated Pipe & Pipe Fittings', 'Manufacturing', '34'),
        '3499': ('Fabricated Metal Products NEC', 'Manufacturing', '34'),
        
        # Industrial Machinery (3500-3599)
        '3511': ('Turbines & Turbine Generators', 'Manufacturing', '35'),
        '3519': ('Internal Combustion Engines NEC', 'Manufacturing', '35'),
        '3523': ('Farm Machinery & Equipment', 'Manufacturing', '35'),
        '3524': ('Lawn & Garden Equipment', 'Manufacturing', '35'),
        '3531': ('Construction Machinery & Equipment', 'Manufacturing', '35'),
        '3532': ('Mining Machinery & Equipment', 'Manufacturing', '35'),
        '3533': ('Oil & Gas Field Machinery', 'Manufacturing', '35'),
        '3534': ('Elevators & Moving Stairways', 'Manufacturing', '35'),
        '3535': ('Conveyors & Conveying Equipment', 'Manufacturing', '35'),
        '3536': ('Hoists, Cranes, Monorails', 'Manufacturing', '35'),
        '3537': ('Industrial Trucks & Tractors', 'Manufacturing', '35'),
        '3541': ('Machine Tools - Machine', 'Manufacturing', '35'),
        '3542': ('Machine Tools - Metal Forming', 'Manufacturing', '35'),
        '3543': ('Industrial Patterns', 'Manufacturing', '35'),
        '3544': ('Special Dies, Tools, Jigs, Dies', 'Manufacturing', '35'),
        '3545': ('Cutting Tools & Accessories', 'Manufacturing', '35'),
        '3546': ('Power Transmission Equipment', 'Manufacturing', '35'),
        '3547': ('Rolling Mill Machinery', 'Manufacturing', '35'),
        '3548': ('Metalworking Machinery NEC', 'Manufacturing', '35'),
        '3549': ('Metalworking Machinery NEC', 'Manufacturing', '35'),
        '3551': ('Food Products Machinery', 'Manufacturing', '35'),
        '3552': ('Textile Machinery', 'Manufacturing', '35'),
        '3553': ('Woodworking Machinery', 'Manufacturing', '35'),
        '3554': ('Paper Industries Machinery', 'Manufacturing', '35'),
        '3555': ('Printing Trades Machinery', 'Manufacturing', '35'),
        '3556': ('Food Products Machinery', 'Manufacturing', '35'),
        '3559': ('Machinery NEC', 'Manufacturing', '35'),
        '3561': ('Pumps & Pumping Equipment', 'Manufacturing', '35'),
        '3562': ('Ball & Roller Bearings', 'Manufacturing', '35'),
        '3563': ('Air & Gas Compressors', 'Manufacturing', '35'),
        '3564': ('Blowers & Fans', 'Manufacturing', '35'),
        '3565': ('Packaging Machinery', 'Manufacturing', '35'),
        '3566': ('Speed Changers, Drives, Gears', 'Manufacturing', '35'),
        '3567': ('Fluid Power Cylinders & Actuators', 'Manufacturing', '35'),
        '3568': ('Mechanical Power Transmission Equip', 'Manufacturing', '35'),
        '3569': ('General Industrial Machinery NEC', 'Manufacturing', '35'),
        '3571': ('Electronic Computers', 'Manufacturing', '35'),
        '3572': ('Computer Storage Devices', 'Manufacturing', '35'),
        '3575': ('Computer Terminals', 'Manufacturing', '35'),
        '3577': ('Computer Peripheral Equipment NEC', 'Manufacturing', '35'),
        '3578': ('Calculating & Accounting Machines', 'Manufacturing', '35'),
        '3582': ('Search, Detection, Navigation Instruments', 'Manufacturing', '35'),
        '3585': ('Air-Conditioning & Warm Air Heating', 'Manufacturing', '35'),
        '3586': ('Measuring & Dispensing Pumps', 'Manufacturing', '35'),
        '3589': ('Service Industry Machines NEC', 'Manufacturing', '35'),
        '3592': ('Carburetors, Pistons, Rings, Valves', 'Manufacturing', '35'),
        '3593': ('Fluid Power Products & Cylinders', 'Manufacturing', '35'),
        '3594': ('Fluid Power Pumps & Motors', 'Manufacturing', '35'),
        '3596': ('Scales & Balances', 'Manufacturing', '35'),
        '3599': ('Machinery NEC', 'Manufacturing', '35'),
        
        # Electronic Equipment (3600-3699)
        '3612': ('Power Distribution & Specialty Transformers', 'Manufacturing', '36'),
        '3613': ('Switchgear & Switchboard Equipment', 'Manufacturing', '36'),
        '3621': ('Motors & Generators', 'Manufacturing', '36'),
        '3622': ('Industrial Controls', 'Manufacturing', '36'),
        '3623': ('Welding Apparatus', 'Manufacturing', '36'),
        '3624': ('Carbon & Graphite Products', 'Manufacturing', '36'),
        '3625': ('Relays & Industrial Controls', 'Manufacturing', '36'),
        '3629': ('Electrical Industrial Apparatus NEC', 'Manufacturing', '36'),
        '3631': ('Household Cooking Equipment', 'Manufacturing', '36'),
        '3632': ('Household Refrigerators & Freezers', 'Manufacturing', '36'),
        '3633': ('Household Laundry Equipment', 'Manufacturing', '36'),
        '3634': ('Electric Hot Water Heaters', 'Manufacturing', '36'),
        '3635': ('Household Vacuum Cleaners', 'Manufacturing', '36'),
        '3639': ('Household Appliances NEC', 'Manufacturing', '36'),
        '3641': ('Electric Lamp Bulbs & Tubes', 'Manufacturing', '36'),
        '3642': ('Lighting Fixtures & Equipment', 'Manufacturing', '36'),
        '3643': ('Current-Carrying Wiring Devices', 'Manufacturing', '36'),
        '3644': ('Noncurrent-Carrying Wiring Devices', 'Manufacturing', '36'),
        '3645': ('Residential Wiring Devices', 'Manufacturing', '36'),
        '3646': ('Commercial, Industrial Wiring Devices', 'Manufacturing', '36'),
        '3647': ('Vehicular Lighting Equipment', 'Manufacturing', '36'),
        '3648': ('Lighting Equipment NEC', 'Manufacturing', '36'),
        '3651': ('Household Audio & Video Equipment', 'Manufacturing', '36'),
        '3652': ('Prerecorded Audio Tapes & Disks', 'Manufacturing', '36'),
        '3661': ('Telephone & Telegraph Apparatus', 'Manufacturing', '36'),
        '3663': ('Radio & TV Broadcasting & Communications Equip', 'Manufacturing', '36'),
        '3664': ('Broadcast, Studio, & Related Equipment', 'Manufacturing', '36'),
        '3665': ('Radio & TV Receiving & Similar Equipment', 'Manufacturing', '36'),
        '3666': ('Communications Equipment NEC', 'Manufacturing', '36'),
        '3671': ('Electron Tubes', 'Manufacturing', '36'),
        '3672': ('Printed Circuit Boards', 'Manufacturing', '36'),
        '3674': ('Semiconductors & Related Devices', 'Manufacturing', '36'),
        '3675': ('Electronic Coils, Transformers, Choppers', 'Manufacturing', '36'),
        '3676': ('Electronic Capacitors', 'Manufacturing', '36'),
        '3677': ('Electronic Resistors', 'Manufacturing', '36'),
        '3678': ('Electronic Connectors', 'Manufacturing', '36'),
        '3679': ('Electronic Components NEC', 'Manufacturing', '36'),
        '3691': ('Storage Batteries', 'Manufacturing', '36'),
        '3692': ('Primary Batteries', 'Manufacturing', '36'),
        '3694': ('Engine Electrical Equipment', 'Manufacturing', '36'),
        '3695': ('Magnetic & Optical Recording Media', 'Manufacturing', '36'),
        '3699': ('Electrical Machinery, Equipment NEC', 'Manufacturing', '36'),
        
        # Transportation Equipment (3700-3799)
        '3711': ('Motor Vehicles', 'Manufacturing', '37'),
        '3712': ('Truck Trailers', 'Manufacturing', '37'),
        '3713': ('Truck Buses', 'Manufacturing', '37'),
        '3714': ('Motor Vehicle Parts & Accessories', 'Manufacturing', '37'),
        '3715': ('Truck Utility Bodies & Trailers', 'Manufacturing', '37'),
        '3716': ('Motor Homes', 'Manufacturing', '37'),
        '3721': ('Aircraft', 'Manufacturing', '37'),
        '3724': ('Aircraft Engines & Engine Parts', 'Manufacturing', '37'),
        '3728': ('Aircraft Parts & Auxiliary Equipment', 'Manufacturing', '37'),
        '3731': ('Ship Building & Repairing', 'Manufacturing', '37'),
        '3732': ('Boat Building & Repairing', 'Manufacturing', '37'),
        '3743': ('Railroad Passenger & Freight Cars', 'Manufacturing', '37'),
        '3799': ('Transportation Equipment NEC', 'Manufacturing', '37'),
        
        # Measuring Instruments (3800-3899)
        '3812': ('Search, Detection, Navigation Instruments', 'Manufacturing', '38'),
        '3821': ('Mechanical Measuring & Controlling Devices', 'Manufacturing', '38'),
        '3822': ('Automatic Controls for Appliances', 'Manufacturing', '38'),
        '3823': ('Industrial Instruments for Measurement', 'Manufacturing', '38'),
        '3824': ('Totalizing Fluid Meters & Counting', 'Manufacturing', '38'),
        '3825': ('Instruments for Measuring & Testing', 'Manufacturing', '38'),
        '3826': ('Laboratory Analytical Instruments', 'Manufacturing', '38'),
        '3829': ('Measuring & Controlling Devices NEC', 'Manufacturing', '38'),
        '3841': ('Surgical & Medical Instruments', 'Manufacturing', '38'),
        '3842': ('Orthopedic, Prosthetic, Surgical Appliances', 'Manufacturing', '38'),
        '3843': ('Dental Equipment & Supplies', 'Manufacturing', '38'),
        '3844': ('X-Ray Apparatus & Tubes', 'Manufacturing', '38'),
        '3845': ('Electromedical Apparatus', 'Manufacturing', '38'),
        '3851': ('Ophthalmic Goods', 'Manufacturing', '38'),
        '3861': ('Photographic Equipment & Supplies', 'Manufacturing', '38'),
        '3873': ('Watches, Clocks, Clockwork Operated', 'Manufacturing', '38'),
        '3899': ('Measuring & Controlling Devices NEC', 'Manufacturing', '38'),
        
        # Miscellaneous Manufacturing (3900-3999)
        '3911': ('Jewelry, Precious Metal', 'Manufacturing', '39'),
        '3914': ('Silverware & Plated Ware', 'Manufacturing', '39'),
        '3915': ('Jewelers\' Materials & Lapidary Work', 'Manufacturing', '39'),
        '3931': ('Musical Instruments', 'Manufacturing', '39'),
        '3942': ('Dolls & Stuffed Toys', 'Manufacturing', '39'),
        '3944': ('Games, Toys, Children\'s Vehicles NEC', 'Manufacturing', '39'),
        '3949': ('Toys & Sporting Goods NEC', 'Manufacturing', '39'),
        '3951': ('Pens, Mechanical Pencils, Parts', 'Manufacturing', '39'),
        '3952': ('Lead Pencils & Art Goods', 'Manufacturing', '39'),
        '3953': ('Marking Devices', 'Manufacturing', '39'),
        '3955': ('Carbon Paper & Inked Ribbons', 'Manufacturing', '39'),
        '3961': ('Costume Jewelry & Novelties', 'Manufacturing', '39'),
        '3965': ('Fasteners, Buttons, Needles', 'Manufacturing', '39'),
        '3991': ('Brooms & Brushes', 'Manufacturing', '39'),
        '3993': ('Signs & Advertising Displays', 'Manufacturing', '39'),
        '3995': ('Wigs & Hairpieces', 'Manufacturing', '39'),
        '3996': ('Linoleum, Asphalted-Felt-Base Floor Covering', 'Manufacturing', '39'),
        '3999': ('Manufacturing Industries NEC', 'Manufacturing', '39'),
        
        # Transportation (4000-4799)
        '4011': ('Railroads', 'Transportation', '40'),
        '4013': ('Railroad Switching & Terminal Services', 'Transportation', '40'),
        '4100': ('Local Passenger Transit', 'Transportation', '41'),
        '4111': ('Local Passenger Transportation', 'Transportation', '41'),
        '4119': ('Local Passenger Transportation NEC', 'Transportation', '41'),
        '4121': ('Taxicabs', 'Transportation', '41'),
        '4131': ('Intercity & Rural Bus Transportation', 'Transportation', '41'),
        '4141': ('Local Bus Charter Service', 'Transportation', '41'),
        '4142': ('Bus Charter Service NEC', 'Transportation', '41'),
        '4151': ('School Buses', 'Transportation', '41'),
        '4173': ('Bus Terminal & Service Facilities', 'Transportation', '41'),
        '4212': ('Local Trucking Without Storage', 'Transportation', '42'),
        '4213': ('Trucking, Except Local', 'Transportation', '42'),
        '4214': ('Local Trucking With Storage', 'Transportation', '42'),
        '4215': ('Courier Services', 'Transportation', '42'),
        '4221': ('Farm Product Warehousing', 'Transportation', '42'),
        '4222': ('Refrigerated Warehousing & Storage', 'Transportation', '42'),
        '4225': ('General Warehousing & Storage', 'Transportation', '42'),
        '4226': ('Special Warehousing & Storage NEC', 'Transportation', '42'),
        '4231': ('Terminal & Joint Terminal Facilities', 'Transportation', '42'),
        '4311': ('U.S. Postal Service', 'Transportation', '43'),
        '4412': ('Deep Sea Foreign Transportation', 'Transportation', '44'),
        '4413': ('Deep Sea Domestic Transportation', 'Transportation', '44'),
        '4422': ('Ferries', 'Transportation', '44'),
        '4424': ('Transatlantic Passenger Service', 'Transportation', '44'),
        '4425': ('Transatlantic Freight Service', 'Transportation', '44'),
        '4432': ('Inland Water Transportation', 'Transportation', '44'),
        '4449': ('Water Transportation Services', 'Transportation', '44'),
        '4481': ('Deep Sea Transportation Services', 'Transportation', '44'),
        '4482': ('Tug & Barge Service', 'Transportation', '44'),
        '4489': ('Water Transportation NEC', 'Transportation', '44'),
        '4511': ('Scheduled Air Transportation', 'Transportation', '45'),
        '4512': ('Scheduled Passenger Air Transportation', 'Transportation', '45'),
        '4513': ('Scheduled Air Freight Transportation', 'Transportation', '45'),
        '4521': ('Nonscheduled Air Transportation', 'Transportation', '45'),
        '4522': ('Charter & Nonscheduled Air Transportation', 'Transportation', '45'),
        '4581': ('Airports, Flying Fields, & Services', 'Transportation', '45'),
        '4612': ('Pipelines (Oil & Gas)', 'Transportation', '46'),
        '4613': ('Pipeline Transportation', 'Transportation', '46'),
        '4619': ('Pipeline Transportation NEC', 'Transportation', '46'),
        '4724': ('Travel Agencies', 'Transportation', '47'),
        '4725': ('Tour Operators', 'Transportation', '47'),
        '4729': ('Passenger Transportation Arrangement NEC', 'Transportation', '47'),
        '4731': ('Freight Transportation Arrangement', 'Transportation', '47'),
        '4789': ('Transportation Services NEC', 'Transportation', '47'),
        
        # Communications (4800-4899)
        '4800': ('Communications', 'Utilities', '48'),
        '4811': ('Telephone Communications', 'Utilities', '48'),
        '4812': ('Radiotelephone Communications', 'Utilities', '48'),
        '4813': ('Telephone Communications', 'Utilities', '48'),
        '4822': ('Telegraph & Other Communications', 'Utilities', '48'),
        '4832': ('Radio Broadcasting Stations', 'Utilities', '48'),
        '4833': ('Television Broadcasting Stations', 'Utilities', '48'),
        '4841': ('Cable & Other Pay Television Services', 'Utilities', '48'),
        '4899': ('Communications Services NEC', 'Utilities', '48'),
        
        # Electric & Gas (4900-4999)
        '4911': ('Electric Services', 'Utilities', '49'),
        '4922': ('Natural Gas Transmission', 'Utilities', '49'),
        '4923': ('Natural Gas Distribution', 'Utilities', '49'),
        '4924': ('Natural Gas Distribution  ', 'Utilities', '49'),
        '4931': ('Electric & Other Services Combined', 'Utilities', '49'),
        '4932': ('Gas & Other Services Combined', 'Utilities', '49'),
        '4939': ('Combination Utilities NEC', 'Utilities', '49'),
        '4941': ('Water Supply & Irrigation Systems', 'Utilities', '49'),
        '4952': ('Sewerage Systems', 'Utilities', '49'),
        '4953': ('Refuse Systems', 'Utilities', '49'),
        '4959': ('Sanitary Services NEC', 'Utilities', '49'),
        
        # Wholesale (5000-5199)
        '5012': ('Automobiles & Auto Parts - Wholesale', 'Wholesale Trade', '50'),
        '5013': ('Motor Vehicleparts & Accessories', 'Wholesale Trade', '50'),
        '5014': ('Tires & Tubes', 'Wholesale Trade', '50'),
        '5015': ('Motor Vehicleparts & Accessories NEC', 'Wholesale Trade', '50'),
        '5021': ('Furniture', 'Wholesale Trade', '50'),
        '5023': ('Homefurnishings', 'Wholesale Trade', '50'),
        '5031': ('Lumber, Plywood, Millwork, Doors', 'Wholesale Trade', '50'),
        '5032': ('Brick, Stone, & Related Materials', 'Wholesale Trade', '50'),
        '5033': ('Roofing, Siding, Insulation Materials', 'Wholesale Trade', '50'),
        '5039': ('Construction Materials NEC', 'Wholesale Trade', '50'),
        '5043': ('Photographic Equipment & Supplies', 'Wholesale Trade', '50'),
        '5044': ('Office Equipment', 'Wholesale Trade', '50'),
        '5045': ('Computers & Computer Equipment', 'Wholesale Trade', '50'),
        '5046': ('Commercial Equipment NEC', 'Wholesale Trade', '50'),
        '5047': ('Medical, Dental, Hospital Equipment', 'Wholesale Trade', '50'),
        '5048': ('Ophthalmic Goods', 'Wholesale Trade', '50'),
        '5049': ('Professional Equipment & Supplies NEC', 'Wholesale Trade', '50'),
        '5050': ('Metals & Minerals NEC', 'Wholesale Trade', '50'),
        '5051': ('Metals & Minerals NEC', 'Wholesale Trade', '50'),
        '5052': ('Coal & Ores', 'Wholesale Trade', '50'),
        '5063': ('Electrical Apparatus & Equipment', 'Wholesale Trade', '50'),
        '5064': ('Electrical Appliances, Televisioning, Parts', 'Wholesale Trade', '50'),
        '5065': ('Electronic Parts & Equipment NEC', 'Wholesale Trade', '50'),
        '5072': ('Hardware', 'Wholesale Trade', '50'),
        '5074': ('Plumbing & Hydronics Supplies', 'Wholesale Trade', '50'),
        '5075': ('Warm Air Heating & Air-Conditioning', 'Wholesale Trade', '50'),
        '5078': ('Refrigeration Equipment & Supplies', 'Wholesale Trade', '50'),
        '5082': ('Engines & Engines Parts', 'Wholesale Trade', '50'),
        '5083': ('Farm & Garden Machinery', 'Wholesale Trade', '50'),
        '5084': ('Industrial Machinery & Equipment', 'Wholesale Trade', '50'),
        '5085': ('Industrial Supplies', 'Wholesale Trade', '50'),
        '5087': ('Service Establishment Equipment & Supplies', 'Wholesale Trade', '50'),
        '5088': ('Transportation Equipment & Supplies NEC', 'Wholesale Trade', '50'),
        '5091': ('Sporting & Recreational Goods & Supplies', 'Wholesale Trade', '50'),
        '5092': ('Toys & Hobby Goods & Supplies', 'Wholesale Trade', '50'),
        '5093': ('Scrap & Waste Materials', 'Wholesale Trade', '50'),
        '5094': ('Jewelry, Watches, Diamonds', 'Wholesale Trade', '50'),
        '5099': ('Durable Goods NEC', 'Wholesale Trade', '50'),
        '5111': ('Printing & Processing Papers', 'Wholesale Trade', '51'),
        '5112': ('Stationery & Office Supplies', 'Wholesale Trade', '51'),
        '5113': ('Industrial & Personal Service Paper', 'Wholesale Trade', '51'),
        '5122': ('Drugs & Drug Products', 'Wholesale Trade', '51'),
        '5136': ('Men\'s & Boys\' Clothing & Accessories', 'Wholesale Trade', '51'),
        '5137': ('Women\'s Children\'s & Infant Clothing', 'Wholesale Trade', '51'),
        '5139': ('Footwear', 'Wholesale Trade', '51'),
        '5141': ('Groceries - General Line', 'Wholesale Trade', '51'),
        '5142': ('Packaged Frozen Foods', 'Wholesale Trade', '51'),
        '5143': ('Dairy Products', 'Wholesale Trade', '51'),
        '5144': ('Poultry & Poultry Products', 'Wholesale Trade', '51'),
        '5145': ('Confectionery', 'Wholesale Trade', '51'),
        '5146': ('Fish & Seafood', 'Wholesale Trade', '51'),
        '5147': ('Meats & Meat Products', 'Wholesale Trade', '51'),
        '5148': ('Fresh Produce', 'Wholesale Trade', '51'),
        '5149': ('Groceries & Related Products NEC', 'Wholesale Trade', '51'),
        '5153': ('Grain & Field Seeds', 'Wholesale Trade', '51'),
        '5154': ('Livestock', 'Wholesale Trade', '51'),
        '5159': ('Farm Products - Raw Materials NEC', 'Wholesale Trade', '51'),
        '5162': ('Plastics Materials & Basic Shapes', 'Wholesale Trade', '51'),
        '5169': ('Chemicals & Allied Products NEC', 'Wholesale Trade', '51'),
        '5171': ('Petroleum Bulk Stations & Terminals', 'Wholesale Trade', '51'),
        '5172': ('Petroleum Products NEC', 'Wholesale Trade', '51'),
        '5181': ('Beer & Ale', 'Wholesale Trade', '51'),
        '5182': ('Wine & Distilled Alcoholic Beverages', 'Wholesale Trade', '51'),
        '5191': ('Farm Supplies', 'Wholesale Trade', '51'),
        '5192': ('Books, Periodicals, Newspapers', 'Wholesale Trade', '51'),
        '5193': ('Flowers, Florists Supplies', 'Wholesale Trade', '51'),
        '5194': ('Tobacco & Tobacco Products', 'Wholesale Trade', '51'),
        '5198': ('Non-Durable Goods NEC', 'Wholesale Trade', '51'),
        '5199': ('Non-Durable Goods NEC', 'Wholesale Trade', '51'),
        
        # Retail (5200-5999)
        '5211': ('Lumber & Other Building Materials Dealers', 'Retail Trade', '52'),
        '5231': ('Paint, Glass, Wallpaper Stores', 'Retail Trade', '52'),
        '5251': ('Hardware Stores', 'Retail Trade', '52'),
        '5261': ('Nursery & Garden Supplies Stores', 'Retail Trade', '52'),
        '5271': ('Mobile Home Dealerships', 'Retail Trade', '52'),
        '5311': ('Department Stores', 'Retail Trade', '53'),
        '5331': ('Variety Stores', 'Retail Trade', '53'),
        '5399': ('Miscellaneous General Merchandise Stores', 'Retail Trade', '53'),
        '5411': ('Grocery Stores', 'Retail Trade', '54'),
        '5421': ('Meat Markets', 'Retail Trade', '54'),
        '5431': ('Fruit & Vegetable Markets', 'Retail Trade', '54'),
        '5441': ('Candy, Nut, Confectionery Stores', 'Retail Trade', '54'),
        '5451': ('Dairy Products Stores', 'Retail Trade', '54'),
        '5461': ('Fish & Seafood Markets', 'Retail Trade', '54'),
        '5499': ('Misc Food Stores', 'Retail Trade', '54'),
        '5511': ('New & Used Car Dealers', 'Retail Trade', '55'),
        '5521': ('Used Car Dealers', 'Retail Trade', '55'),
        '5531': ('Auto & Home Supply Stores', 'Retail Trade', '55'),
        '5541': ('Gasoline Service Stations', 'Retail Trade', '55'),
        '5551': ('Boat Dealers', 'Retail Trade', '55'),
        '5561': ('Recreational Vehicle Dealers', 'Retail Trade', '55'),
        '5571': ('Motorcycle Dealers', 'Retail Trade', '55'),
        '5599': ('Auto Dealers NEC', 'Retail Trade', '55'),
        '5611': ('Men\'s & Boys\' Clothing Stores', 'Retail Trade', '56'),
        '5621': ('Women\'s Clothing Stores', 'Retail Trade', '56'),
        '5631': ('Women\'s Accessory & Specialty Stores', 'Retail Trade', '56'),
        '5641': ('Children\'s & Infants\' Wear Stores', 'Retail Trade', '56'),
        '5651': ('Family Clothing Stores', 'Retail Trade', '56'),
        '5661': ('Shoe Stores', 'Retail Trade', '56'),
        '5699': ('Clothing Stores NEC', 'Retail Trade', '56'),
        '5712': ('Furniture Stores', 'Retail Trade', '57'),
        '5713': ('Floor Covering Stores', 'Retail Trade', '57'),
        '5714': ('Drapery, Curtain, Linens Stores', 'Retail Trade', '57'),
        '5719': ('Home Furnishings Stores NEC', 'Retail Trade', '57'),
        '5722': ('Household Appliance Stores', 'Retail Trade', '57'),
        '5731': ('Radio, Television Stores', 'Retail Trade', '57'),
        '5734': ('Musical Instrument Stores', 'Retail Trade', '57'),
        '5735': ('Hobby, Toy, Game Stores', 'Retail Trade', '57'),
        '5736': ('Camera & Photographic Supply Stores', 'Retail Trade', '57'),
        '5812': ('Eating Places', 'Retail Trade', '58'),
        '5813': ('Drinking Places', 'Retail Trade', '58'),
        '5814': ('Food & Drinking Places', 'Retail Trade', '58'),
        '5921': ('Drug Stores & Proprietary Stores', 'Retail Trade', '59'),
        '5932': ('Used Merchandise Stores', 'Retail Trade', '59'),
        '5943': ('Sporting Goods Stores', 'Retail Trade', '59'),
        '5944': ('Jewelry Stores', 'Retail Trade', '59'),
        '5945': ('Hobby, Toy, Game Shops', 'Retail Trade', '59'),
        '5946': ('Camera & Photographic Supply Stores', 'Retail Trade', '59'),
        '5947': ('Gift, Novelty, Souvenir Stores', 'Retail Trade', '59'),
        '5948': ('Luggage & Leather Goods Stores', 'Retail Trade', '59'),
        '5949': ('Sewing, Needlework, Piece Goods Stores', 'Retail Trade', '59'),
        '5961': ('Catalog & Mail-Order Houses', 'Retail Trade', '59'),
        '5962': ('Automatic Vending Machine Operators', 'Retail Trade', '59'),
        '5963': ('Direct Selling Organizations', 'Retail Trade', '59'),
        '5983': ('Fuel Oil Dealers', 'Retail Trade', '59'),
        '5984': ('Liquefied Petroleum Gas Dealers', 'Retail Trade', '59'),
        '5989': ('Miscellaneous Retail Stores NEC', 'Retail Trade', '59'),
        
        # Finance (6000-6799)
        '6011': ('Federal Reserve Banks', 'Finance', '60'),
        '6019': ('Central Reserve Depository Institutions', 'Finance', '60'),
        '6021': ('National Banks', 'Finance', '60'),
        '6022': ('State Banks', 'Finance', '60'),
        '6029': ('Depository Institutions NEC', 'Finance', '60'),
        '6035': ('Savings Institutions', 'Finance', '60'),
        '6036': ('Savings Banks', 'Finance', '60'),
        '6061': ('Credit Unions', 'Finance', '60'),
        '6099': ('Functions Related to Banking NEC', 'Finance', '60'),
        '6111': ('Federal & Federally Sponsored Credit', 'Finance', '61'),
        '6112': ('Credit Unions', 'Finance', '61'),
        '6113': ('Industrial Loan Companies', 'Finance', '61'),
        '6141': ('Personal Finance Companies', 'Finance', '61'),
        '6153': ('Short-Term Business Credit Institutions', 'Finance', '61'),
        '6159': ('Miscellaneous Business Credit Institutions', 'Finance', '61'),
        '6162': ('Mortgage Bankers & Correspondents', 'Finance', '61'),
        '6163': ('Loan Brokers', 'Finance', '61'),
        '6199': ('Finance Services NEC', 'Finance', '61'),
        '6211': ('Security Brokers, Dealers, & Flotation', 'Finance', '62'),
        '6213': ('Stock Exchanges', 'Finance', '62'),
        '6221': ('Commodity Contracts Brokers & Dealers', 'Finance', '62'),
        '6231': ('Security & Commodity Exchanges', 'Finance', '62'),
        '6282': ('Investment Advice', 'Finance', '62'),
        '6289': ('Services Allied With Stock Exchange NEC', 'Finance', '62'),
        '6311': ('Life Insurance', 'Finance', '63'),
        '6321': ('Accident & Health Insurance', 'Finance', '63'),
        '6324': ('Hospital & Medical Service Plans', 'Finance', '63'),
        '6331': ('Fire, Marine, Casualty Insurance', 'Finance', '63'),
        '6351': ('Surety Insurance', 'Finance', '63'),
        '6361': ('Title Insurance', 'Finance', '63'),
        '6371': ('Pension, Health, Welfare Funds', 'Finance', '63'),
        '6399': ('Insurance Carriers NEC', 'Finance', '63'),
        '6411': ('Insurance Agents, Brokers, Service', 'Finance', '64'),
        '6412': ('Insurance Agents, Brokers, & Service', 'Finance', '64'),
        '6500': ('Real Estate Operators & Lessors', 'Real Estate', '65'),
        '6510': ('Lessors of Buildings', 'Real Estate', '65'),
        '6512': ('Nonresidential Building Operators', 'Real Estate', '65'),
        '6513': ('Apartment Building Operators', 'Real Estate', '65'),
        '6514': ('Dwelling Operators', 'Real Estate', '65'),
        '6515': ('Mobile Home Site Operators', 'Real Estate', '65'),
        '6517': ('Storage Facility Operators', 'Real Estate', '65'),
        '6519': ('Building Operators NEC', 'Real Estate', '65'),
        '6531': ('Real Estate Agents & Managers', 'Real Estate', '65'),
        '6541': ('Title Abstract Offices', 'Real Estate', '65'),
        '6552': ('Subdividers & Developers', 'Real Estate', '65'),
        '6798': ('Invest-in Offices & Closed-End Investment', 'Finance', '67'),
        '6799': ('Investors NEC', 'Finance', '67'),
        '6770': ('Blank Checks', 'Finance', '67'),
        
        # Professional Services (8700-8799)
        '8711': ('Engineering Services', 'Professional Services', '87'),
        '8712': ('Architect & Engineering Services', 'Professional Services', '87'),
        '8713': ('Surveying Services', 'Professional Services', '87'),
        '8721': ('Accounting, Auditing, Bookkeeping', 'Professional Services', '87'),
        '8742': ('Management Consulting Services', 'Professional Services', '87'),
        '8748': ('Business Consulting Services NEC', 'Professional Services', '87'),
        
        # Services (7000-8999)
        '7011': ('Hotels & Motels', 'Services', '70'),
        '7021': ('Rooming & Boarding Houses', 'Services', '70'),
        '7031': ('Sporting & Recreational Camps', 'Services', '70'),
        '7032': ('Camps & Recreational Vehicle Parks', 'Services', '70'),
        '7033': ('Trailer Parks & Campsites', 'Services', '70'),
        '7041': ('Membership-based Organization Hotels', 'Services', '70'),
        '7211': ('Power Laundries', 'Services', '72'),
        '7212': ('Garment Pressing, Cleaning Shops', 'Services', '72'),
        '7213': ('Linen Supply', 'Services', '72'),
        '7215': ('Coin-Operated Laundries & Cleaning', 'Services', '72'),
        '7216': ('Drycleaning Plants', 'Services', '72'),
        '7217': ('Carpet & Upholstery Cleaning', 'Services', '72'),
        '7219': ('Laundry, Cleaning Services NEC', 'Services', '72'),
        '7221': ('Photographic Studios', 'Services', '72'),
        '7231': ('Beauty Shops', 'Services', '72'),
        '7241': ('Barber Shops', 'Services', '72'),
        '7251': ('Shoe Repair & Shoeshine Parlors', 'Services', '72'),
        '7261': ('Funeral Services & Crematories', 'Services', '72'),
        '7299': ('Miscellaneous Personal Services NEC', 'Services', '72'),
        '7311': ('Advertising Agencies', 'Services', '73'),
        '7312': ('Outdoor Advertising', 'Services', '73'),
        '7313': ('Radio, TV, Publisher Representatives', 'Services', '73'),
        '7319': ('Advertising Services NEC', 'Services', '73'),
        '7321': ('Credit Reporting Services', 'Services', '73'),
        '7322': ('Adjustment & Collection Services', 'Services', '73'),
        '7323': ('Credit Reporting & Collection Agencies', 'Services', '73'),
        '7331': ('Direct Mail Advertising Services', 'Services', '73'),
        '7338': ('Secretarial & Court Reporting Services', 'Services', '73'),
        '7342': ('Disinfecting & Pest Control', 'Services', '73'),
        '7349': ('Building Maintenance Services NEC', 'Services', '73'),
        '7352': ('Medical Equipment Rental & Leasing', 'Services', '73'),
        '7359': ('Equipment Rental & Leasing NEC', 'Services', '73'),
        '7361': ('Employment Agencies', 'Services', '73'),
        '7363': ('Help Supply Services', 'Services', '73'),
        '7371': ('Computer Programming Services', 'Services', '73'),
        '7372': ('Services to Prewritten Software', 'Services', '73'),
        '7373': ('Computer Integrated System Design', 'Services', '73'),
        '7374': ('Data Processing & Preparation', 'Services', '73'),
        '7375': ('Information Retrieval Services', 'Services', '73'),
        '7376': ('Computer Facilities Management', 'Services', '73'),
        '7377': ('Computer Rental & Leasing', 'Services', '73'),
        '7378': ('Computer Maintenance & Repair', 'Services', '73'),
        '7379': ('Computer Related Services NEC', 'Services', '73'),
        '7381': ('Detective & Protective Services', 'Services', '73'),
        '7382': ('Security Systems Services', 'Services', '73'),
        '7383': ('News Syndicates', 'Services', '73'),
        '7384': ('Photofinishing Laboratories', 'Services', '73'),
        '7385': ('Telephone Answering Services', 'Services', '73'),
        '7389': ('Business Services NEC', 'Services', '73'),
        '7511': ('Automobile Rental', 'Services', '75'),
        '7512': ('Automobile Leasing', 'Services', '75'),
        '7513': ('Truck Rental & Leasing', 'Services', '75'),
        '7514': ('Passenger Car Rental', 'Services', '75'),
        '7515': ('Passenger Car Leasing', 'Services', '75'),
        '7519': ('Automobile Rental, Leasing NEC', 'Services', '75'),
        '7521': ('Automobile Parking', 'Services', '75'),
        '7532': ('Top, Body Repair, Paint Shops', 'Services', '75'),
        '7533': ('Automotive Exhaust System Repair', 'Services', '75'),
        '7534': ('Tire Retreading & Repair Shops', 'Services', '75'),
        '7535': ('Automotive Glass Repair Shops', 'Services', '75'),
        '7536': ('Automotive Transmission Repair Shops', 'Services', '75'),
        '7537': ('Automotive Repair Shops NEC', 'Services', '75'),
        '7538': ('General Automotive Repair Shops', 'Services', '75'),
        '7539': ('Automotive Repair, Services NEC', 'Services', '75'),
        '7542': ('Car Washes', 'Services', '75'),
        '7549': ('Automobile Services NEC', 'Services', '75'),
        '7622': ('Radio & TV Repair Shops', 'Services', '76'),
        '7623': ('Electronic Repair Shops', 'Services', '76'),
        '7629': ('Electrical & Electronic Repair NEC', 'Services', '76'),
        '7631': ('Watch, Clock, Jewelry Repair', 'Services', '76'),
        '7641': ('Reupholstery & Furniture Repair', 'Services', '76'),
        '7699': ('Miscellaneous Repair Shops NEC', 'Services', '76'),
        '7812': ('Motion Picture & Video Production', 'Services', '78'),
        '7819': ('Motion Picture & Video Services NEC', 'Services', '78'),
        '7822': ('Motion Picture & Video Distribution', 'Services', '78'),
        '7829': ('Services Allied With Film Distribution', 'Services', '78'),
        '7832': ('Motion Picture, Video Rental', 'Services', '78'),
        '7833': ('Film Libraries', 'Services', '78'),
        '7841': ('Video Tape Rental', 'Services', '78'),
        '7911': ('Dance Halls, Studios, Schools', 'Services', '79'),
        '7922': ('Theatrical Producers, Misc Services', 'Services', '79'),
        '7929': ('Entertainers & Entertainment Services NEC', 'Services', '79'),
        '7933': ('Bowling Alleys', 'Services', '79'),
        '7941': ('Sports Clubs, Promoters', 'Services', '79'),
        '7948': ('Racing, Including Track Operations', 'Services', '79'),
        '7992': ('Public Golf Courses', 'Services', '79'),
        '7993': ('Coin-Operated Amusement Devices', 'Services', '79'),
        '7996': ('Amusement Parks', 'Services', '79'),
        '7999': ('Amusement, Recreation Services NEC', 'Services', '79'),
        '8011': ('Offices of Doctors of Medicine', 'Services', '80'),
        '8021': ('Offices of Dentists', 'Services', '80'),
        '8031': ('Offices of Osteopaths', 'Services', '80'),
        '8041': ('Offices of Chiropractors', 'Services', '80'),
        '8042': ('Offices of Optometrists', 'Services', '80'),
        '8043': ('Offices of Podiatrists', 'Services', '80'),
        '8049': ('Offices of Health Practitioners NEC', 'Services', '80'),
        '8071': ('Medical Laboratories', 'Services', '80'),
        '8072': ('Dental Laboratories', 'Services', '80'),
        '8082': ('Home Health Care Services', 'Services', '80'),
        '8083': ('Care Facilities for Developmentally Disabled', 'Services', '80'),
        '8084': ('Kidney Dialysis Centers', 'Services', '80'),
        '8085': ('Nursing Care Facilities', 'Services', '80'),
        '8086': ('Psychiatric Hospitals', 'Services', '80'),
        '8087': ('Specialty Outpatient Facilities', 'Services', '80'),
        '8088': ('Ambulatory Surgical Centers', 'Services', '80'),
        '8092': ('Kidney Dialysis Centers', 'Services', '80'),
        '8093': ('Specialty Outpatient Facilities NEC', 'Services', '80'),
        '8099': ('Health Care Services NEC', 'Services', '80'),
        '8111': ('Legal Services', 'Professional Services', '81'),
        '8211': ('Elementary & Secondary Schools', 'Services', '82'),
        '8221': ('Colleges & Universities', 'Services', '82'),
        '8222': ('Colleges, Universities, Junior Colleges', 'Services', '82'),
        '8231': ('Libraries', 'Services', '82'),
        '8249': ('Educational Services NEC', 'Services', '82'),
        '8299': ('Schools & Educational Services NEC', 'Services', '82'),
        '8322': ('Individual & Family Services', 'Services', '83'),
        '8331': ('Job Training & Related Services', 'Services', '83'),
        '8351': ('Childcare Services', 'Services', '83'),
        '8361': ('Residential Care Facilities', 'Services', '83'),
        '8399': ('Social Services NEC', 'Services', '83'),
        '8412': ('Museums & Art Galleries', 'Services', '84'),
        '8422': ('Arboretums & Botanical Gardens', 'Services', '84'),
        '8611': ('Labor Organizations', 'Services', '86'),
        '8621': ('Professional Membership Organizations', 'Services', '86'),
        '8631': ('Religious Organizations', 'Services', '86'),
        '8641': ('Civic & Social Organizations', 'Services', '86'),
        '8651': ('Political Organizations', 'Services', '86'),
        '8661': ('Religious Organizations', 'Services', '86'),
        '8699': ('Membership Organizations NEC', 'Services', '86'),
        '8811': ('Private Households', 'Services', '88'),
        '8821': ('Automotive Services', 'Services', '88'),
        '8899': ('Services NEC', 'Services', '89'),
    }
    
    df = pd.DataFrame(
        [(k, v[0], v[1], v[2]) for k, v in sic_data.items()],
        columns=['sic', 'sic_description', 'sector_name', 'sic_2digit']
    )
    
    return df


def main():
    """Update SIC lookup with comprehensive 4-digit mapping"""
    
    print("\nUpdating comprehensive SIC industry lookup...")
    
    sic_lookup = create_comprehensive_sic_lookup()
    output_path = "data/sec/external/sic_industry_names.csv"
    
    sic_lookup.to_csv(output_path, index=False)
    
    print(f"✅ Updated SIC lookup: {output_path}")
    print(f"   Rows: {len(sic_lookup)}")
    print(f"   Unique sectors: {sic_lookup['sector_name'].nunique()}")
    print(f"\nSector Summary:")
    print(sic_lookup.groupby('sector_name').size().sort_values(ascending=False).to_string())


if __name__ == "__main__":
    main()
